engines:
  csslint:
    enabled: true
  duplication:
    config:
      languages:
        -
          javascript: ~
    enabled: true
  eslint: 
    enabled: true
  markdownlint: 
    enabled: true
  shellcheck: 
    enabled: true
ratings: 
  exclude_paths: 
    - "test/"
    - "test_new_structure/"
    - "**/bower_components"
    - "**/node_modules"
    - "**/vendor"
  paths: 
    - src/**
    - public/app/**
    - conf/**
